### ISSUE TITLE
Linux build failure due to "Exec"

### ISSUE THREAD

**Issue by cjbj** [n-riesco/oracledb-electron-builder#2]
To build on Linux, I had to remove this line:
```
     "Exec": "oracledb-example-app",
```

This line was causing the build to fail with:
```
Error: Please specify executable name as linux.executableName instead of linux.desktop.Exec
```
The name is already given by `"executableName"`.

FWIW, being on an RPM based system, I also preferred to build an rpm:

```
      "target": [
        "rpm"
      ]
```

**Comment by n-riesco** [comment]
This failure started with [electron-builder 20.31.0](https://github.com/electron-userland/electron-builder/releases/tag/v20.31.0).

I'll remove `linux.desktop.Exec`.

---

I'll keep `AppImage` as the target, since it works for both `rpm` and `deb` distributions and requires no admin rights to run the image.
